# Generated by Django 3.2.9 on 2021-11-15 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок объявления')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Информация об объявлении')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('address', models.CharField(max_length=128, verbose_name='Адресс')),
                ('photo', models.ImageField(upload_to='uploads/', verbose_name='Фото')),
                ('is_liked', models.BooleanField(default=False, verbose_name='Пользователь поставил лайк')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('advt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advt.advert')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст комментария')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('advt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advt.advert')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'advt'), name='unique_like'),
        ),
    ]
